def appName='dragon-ball'

pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'prod'], description: 'Ambiente')
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh """
                docker build -t ${appName}:${params.ENVIRONMENT} .
                """
            }
        }

    stage('Deploy') {
    steps {
        script {

            def PORT = ""

            if (params.ENVIRONMENT == "dev") {
                PORT = "4200"
            } else if (params.ENVIRONMENT == "qa") {
                PORT = "4300"
            } else {
                PORT = "80"
            }

            sh """
                docker stop ${appName}-${params.ENVIRONMENT} || true
                docker rm ${appName}-${params.ENVIRONMENT} || true

                docker run -d \
                  -p ${PORT}:80 \
                  --name ${appName}-${params.ENVIRONMENT} \
                  ${appName}:${params.ENVIRONMENT}
            """
        }
    }
}
    }
}