pipeline {
    agent any

    environment {
        IMAGE_NAME = "angular-app"
        BRANCH = "main"   // 👈 define aquí tu rama
    }

    stages {

        stage('Build Docker Image') {
            steps {
                script {

                    if (BRANCH == "develop") {
                        sh "docker build -t ${IMAGE_NAME}:dev ."
                    }

                    if (BRANCH == "release") {
                        sh "docker build -t ${IMAGE_NAME}:test ."
                    }

                    if (BRANCH == "main") {
                        sh "docker build -t ${IMAGE_NAME}:prod ."
                    }

                }
            }
        }

        stage('Deploy') {
            steps {
                script {

                    if (BRANCH == "develop") {
                        sh """
                        docker rm -f angular-dev || true
                        docker run -d -p 4201:80 --name angular-dev ${IMAGE_NAME}:dev
                        """
                    }

                    if (BRANCH == "release") {
                        sh """
                        docker rm -f angular-test || true
                        docker run -d -p 4202:80 --name angular-test ${IMAGE_NAME}:test
                        """
                    }

                    if (BRANCH == "main") {
                        sh """
                        docker rm -f angular-prod || true
                        docker run -d -p 80:80 --name angular-prod ${IMAGE_NAME}:prod
                        """
                    }

                }
            }
        }
    }
}